---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bwoq1navr8n2/public_html/
    - /bin/cp -R scrprints $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
